name: OllamaCode
options:
  bundleIdPrefix: com.ollamacode
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "13.0"
    CODE_SIGN_STYLE: Automatic
    ENABLE_HARDENED_RUNTIME: YES
    CODE_SIGN_ENTITLEMENTS: OllamaCode/Resources/OllamaCode.entitlements

packages:
  SQLite.swift:
    url: https://github.com/stephencelis/SQLite.swift.git
    from: "0.15.0"

targets:
  OllamaCode:
    type: application
    platform: macOS
    sources:
      - path: OllamaCode
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ollamacode.app
        INFOPLIST_FILE: OllamaCode/Resources/Info.plist
        PRODUCT_NAME: OllamaCode
        MARKETING_VERSION: "2.1.0"
        CURRENT_PROJECT_VERSION: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        COMBINE_HIDPI_IMAGES: YES
    dependencies:
      - package: SQLite.swift
        product: SQLite
    entitlements:
      path: OllamaCode/Resources/OllamaCode.entitlements
      properties:
        com.apple.security.app-sandbox: false
        com.apple.security.files.user-selected.read-write: true
        com.apple.security.network.client: true

  OllamaCodeTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: OllamaCodeTests
    dependencies:
      - target: OllamaCode

schemes:
  OllamaCode:
    build:
      targets:
        OllamaCode: all
    run:
      config: Debug
    test:
      targets:
        - OllamaCodeTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
